name: Publish Docker Image and Notify

on:
  workflow_run:
    workflows: ["Build Docker Image"]  # Ensure this matches the exact name of your build workflow
    types:
      - completed

jobs:
  publish-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull shirishkc/grafana:latest

      - name: Send Discord notification on success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
             "content": "**[ SUCCESS ] Docker image shirishkc/grafana:latest published successfully to Docker Hub!**"
          }' ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord notification on failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
             "content": "**[ FAILURE ] Docker image shirishkc/grafana:latest failed to publish to Docker Hub!**"
          }' ${{ secrets.DISCORD_WEBHOOK }}

  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Job
        run: echo "This is a dummy job to satisfy the GitHub Actions requirement."

